#! /bin/bash
terminal=
while getopts t name
do
    case $name in 
        t) terminal=1;;
        ?) ;;
    esac
done
shift $(($OPTIND - 1))
if [[ -z $terminal ]]
then
    emacsclient -c -a "" "$@" >/dev/null & 
    disown
else
    emacsclient -t -a "" "$@"
fi
